- client/src/components/matches/matches.component.js
removed roommates tab and displayed listings on mount
> refactored explore page

- client/src/components/matches/matches.component.js
Reverts VHomes-Group/VHomes_v2#95
> Revert "refactored explore page"

- client/package-lock.json
- client/package.json
- client/src/App.js
- client/src/components/editListing/editListing.js
- client/src/components/matches/listing/listingCard.component.js
- client/src/index.js
- client/src/redux/actions/editListingActions.js
- client/src/redux/actions/loadingActions.js
- client/src/redux/actions/searchListingActions.js
- client/src/redux/configureStore.js
- client/src/redux/reducers/loadingReducer.js
- server/models/listing.model.js
- server/routes/listing.js
connected edit listing to back and added loading states
> added connected-react-router to allow for redux to push to history.

- src/components/matches/listing/listingCard.component.js
- src/components/matches/listing/listings.component.js
- src/components/matches/listing/listings.css
> updated listingCard navlink to not surround affect the surrounding area

- src/components/createListing/datesCL.component.js
> removed reset button from create listing calendar

- src/components/listingPage/listingPage.component.js
- src/redux/actions/calendarSyncActions.js
> fixed calendar sync on listing page mount

- src/components/matches/listing/listings.component.js
> Added sorting functionality for buttons on listings.  Sorted by newest by default

- src/components/createListing/createListing.component.js
- src/components/createListing/photos/photoUploadRequests.js
- src/components/editListing/editListing.js
- src/components/listingPage/listingPage.component.js
- src/components/matches/listing/listingCard.component.js
- src/components/matches/listing/listings.component.js
- src/components/reservations/reservationCard.component.js
- src/redux/actions/searchListingActions.js
TODO:
-[x] add "save draft" button to create listing but not activate it
-[x] change Explore page to display active listings only
-[x] add indicator on MyListings listing cards and individual listing pages for draft listings
-[x] Edit Listings for draft listings should have an option to submit
closes #329
> listing draft changes

- src/components/editListing/editListing.js
- src/components/listingPage/listingPage.component.js
- src/components/matches/listing/listingCard.component.js
- src/components/myAccount/menu.component.js
- src/components/reservations/reservationCard.component.js
- src/redux/actions/authActions.js
- src/redux/actions/transferListingActions.js
- src/redux/configureStore.js
- src/redux/reducers/transferListingReducer.js
- src/utils/fetchRequest.js
1. Added redux actions to getListingTransferRequests and sendListingTransferRequest.
2. Added redux reducer for getting transfer requests.  
3. Added my requests tab to menu.component.
4. Updated ReservationCard to be a class component.  
5. Updated handleReq to get token from store.
6. Added visual for transfers and accept button for each transfer.
TODO: 
~~Update routes still passing in token as an argument~~ -> Saved for later.
> Transfer Listings and tweaks.

- src/components/matches/listing/listingCard.component.js
- src/components/matches/listing/listings.component.js
- src/components/myAccount/menu.component.js
- src/components/reservations/reservationCard.component.js
- src/redux/actions/transferListingActions.js
- src/redux/reducers/transferListingReducer.js
- src/utils/fetchRequest.js
Issues fixed:
1. Different font for when there are no listings
2. Transfer not displaying due to incorrect conditional rendering
> Connected rejection route to redux.  Added redux dispatch to buttons for Reject / Reject all. Corrected minor issues (see comment)

- public/css/common.css
- src/components/homePage/navbar.component.js
> Mobile navbar

- src/components/homePage/newHome.component.js
> changed subscription popup to display once only

- package-lock.json
- package.json
- src/App.js
- src/components/homePage/featuredListing.css
- src/components/homePage/featuredListings.component.js
- src/components/homePage/newHome.component.js
- src/components/listingPage/listingPage.component.js
- src/components/matches/listing/HorizontalListingCard.component.js
- src/redux/actions/searchListingActions.js
- src/redux/reducers/searchListingReducer.js
> Popular listings homepage

- src/components/editListing/editListing.css
- src/components/editListing/editListing.js
- src/components/listingPage/listingPage.component.js
> export listing on edit listing page

- src/components/homePage/featuredListings.component.js
- src/components/reservations/reservationLookupModal.component.js
- src/components/reservations/reservationLookupModal.css
> Reservation modal

- src/components/homePage/footer.component.js
- src/components/subpages/contact.component.js
- src/components/subpages/contact.css
> Contact page

- public/css/common.css
- src/components/homePage/navbar.component.js
- src/components/reservations/reservationLookupModal.component.js
- src/components/reservations/reservationLookupModal.css
> fix reservation modal bug of staying open on click off

- src/components/createListing/createListing.css
> remove red outline from price input in createListing

- src/components/createListing/createListing.component.js
> cast details as int in create listing

- src/components/homePage/footer.component.js
> update footer social links

- src/components/editListing/editListing.js
- src/components/listingPage/listingPage.component.js
- src/components/listingPage/listingPage.css
- src/components/matches/listing/HorizontalListingCard.component.js
> button to deactivate listing, small style fixes

- src/components/listingPage/listingPage.component.js
- src/components/listingPage/listingPage.css
> Add "Edit Listing" button to listing page

- src/components/subpages/about.component.js
- src/components/subpages/aboutus.css
> add mobile responsiveness to about us page

- src/components/createListing/createListing.component.js
> hot fix for create listing stripeId bug

- src/components/createListing/createListing.component.js
- src/redux/actions/calendarSyncActions.js
> listing calendar import bug fixes

- public/index.html
- src/components/listingPage/listingPage.component.js
> added map to individual listing

- src/components/listingPage/listingPage.component.js
> style map in individual listing pages within location section

- src/components/matches/listing/horizontalscrollmenu.css
- src/components/matches/listing/listings.component.js
- src/components/matches/listing/listings.css
- src/components/myAccount/menu.css
> add filter in account section for draft listings

- src/redux/actions/authActions.js
closes #463 
- Invalid credentials on sign in should display an error message
> fixed login bug on invalid credentials

- src/components/authentication/GoogleSignIn.js
- src/redux/actions/authActions.js
> fixed google auto sign on

- package-lock.json
- package.json
- public/abstract-user-flat-4.svg:Zone.Identifier
- public/images/abstract-user-flat-4.svg
- src/components/myAccount/imageCrop.component.js
- src/components/myAccount/imageCrop.css
- src/components/myAccount/profile.component.js
- src/components/myAccount/profile.css
- src/redux/actions/userActions.js
- src/redux/reducers/userReducer.js
closes #357 
- Have not added styling
- Requires backend changes
> updated my profile to have pfp

- public/abstract-user-flat-4.svg:Zone.Identifier
Removed identifier file -> Issues with pulling from master.
> removed identifier file

- package-lock.json
- src/components/myAccount/menu.component.js
- src/components/myAccount/payout.component.js
- src/components/myAccount/payout.css
> Stripe Payouts

- public/index.html
- src/components/createListing/createListing.component.js
- src/components/homePage/footer.component.js
- src/components/homePage/newHome.component.js
- src/components/listingPage/paymentSuccess.component.js
- src/components/reservations/reservationLookupModal.component.js
- src/components/subpages/about.component.js
Closes #467
- Changed all Λ's to a's
- Frontend should run without error
- All instances of "NomΛd" should be replaced with "Nomad"
> Updated upside down V to a

- package-lock.json
- src/components/myAccount/payout.component.js
- src/components/myAccount/payout.css
Issue #473 
Fixed styling issue caused by naming css class `container`, changed classname to `stripe-container`
Old: 
New: 
Start the site and see if the change applied :0
> Styling Issue with the "Why Nomad?" section

- src/utils/axiosConfig.js
- src/utils/fetchRequest.js
N/A
- Hotfix for production server URL, changed to api.visitnomad.com
N/A
> Changed api url to api.visitnomad.com

- src/components/authentication/GoogleSignIn.js
- src/components/authentication/signup.component.js
- src/redux/actions/authActions.js
Closes #477
- Added "Sign up with Google" button to Sign Up page
- Split functionality between login and sign up with Google
**1. Verify that new users cannot create an account on login page**
- Select "Log in with Google" on the login page. 
- Sign in with a new account (cannot be an account already registered in the database). 
- VERIFY: the following error should display
**2. Verify that signing up with Google is compatible with "Are you a host?" button**
- Check the "Are you a host?" button on the sign up page.
- Select "Sign up with Google" and sign in with a new account.
- Once signed in, navigate to MyAccount.
- VERIFY: MyAccount should include a tab called "MyListings"
- VERIFY: the email associated with the account should receive the following email
**3. Verify that signing up …
> Split signup and login with Google functionality

- src/components/authentication/GoogleSignIn.js
- src/redux/actions/authActions.js
Closes #437 
- Generated Google OAuth 2.0 token with staynomadhomes@gmail.com account
- Provisioned access to visitnomad.com and localhost:3000 domains
- Updated Google sign on integration to use new OAuth token
- User should be able to log in / sign up via Google SSO on http://localhost3000 
- User should be able to log in / sign up via Google SSO on https://staging.visitnomad.com (this can only be tested once pushed to staging environment)
> Changed google sso to use staynomadhomes token
